# Generated by Django 5.0.2 on 2024-03-18 17:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
