# Generated by Django 5.0.2 on 2024-03-19 17:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
